### PR TITLE
Update the     README.md file to describe the     repo.

### PR DESCRIPTION
**Pull request by ayomide321**

### CODE REVIEW

**Review by freeboson — COMMENTED** [review]
This only adds your name to the readme — didn't you want to describe the repo?

**Comment by freeboson** [comment]
This PR now has a _lot_ of commits in it, but doesn't match the description. It would be good to make one PR changing the readme as desired, then another PR with the other changes. Keep the PRs focused and atomic.

**Comment by ayomide321** [comment]
I tried, however it won’t let me make a different pull request.

**Comment by freeboson** [comment]
OK, well since this makes almost no change to README, why don't you update the PR title (and add a description) about what actually _is_ in the PR?

**Comment by freeboson** [comment]
Here's how to move the most recent n commits from one branch into another: https://stackoverflow.com/a/1628584

**Comment by freeboson** [comment]
What's the status of this PR? It looks like you added more commits, was that intentional? Can you please make the requested changes?

**Comment by ayomide321** [comment]
I tried to make a new branch with the new commits. I don’t know if I did it
right or not.

**Comment by freeboson** [comment]
Closing this in favor of https://github.com/ayomide321/step/pull/3 which has the same work.

**Pull request closed without merging**
